inherit_from: .rubocop_todo.yml

# db/* excludes below should not override the rubocop-provided default excludes
# @see https://github.com/rubocop-hq/rubocop/issues/6398
inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - db/migrate/**
    - db/schema.rb

Rails:
  Enabled: true
