sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.3
before_install:
  - gem update --system
  - gem install bundler
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up bundle install
jdk:
  - oraclejdk8
